- type: loadout
  id: LoadoutSecurityUniformGrey
  name: Сірий комбінезон безпеки
  description: An alternate job equipment.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - SecurityOfficer
    - SecurityCadet
    - Warden
  item: ClothingUniformJumpsuitSecGrey

- type: loadout
  id: LoadoutSecurityOuterArmorBasic
  name: Базовий бронежилет
  description: An alternate job equipment.
  category: Jobs
  cost: 4
  exclusive: true
  jobWhitelist:
    - SecurityOfficer
    - SeniorOfficer
  item: ClothingOuterArmorBasic

- type: loadout
  id: LoadoutSecurityHeadHelmetBasic
  name: Звичайний шолом
  description: An alternate job equipment.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - SecurityOfficer
    - SeniorOfficer
  item: ClothingHeadHelmetBasic

- type: loadout
  id: LoadoutSecurityMaskGasSwat
  name: SWAT Газ маска
  description: An alternate job equipment.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - SecurityOfficer
    - SecurityCadet
    - Warden
    - HeadOfSecurity
  item: ClothingMaskGasSwat

- type: loadout
  id: LoadoutSecurityEyesGlasses
  name: Охоронні окуляри
  description: An alternate job equipment.
  category: Jobs
  cost: 1
  exclusive: true
  jobWhitelist:
    - SecurityOfficer
    - SecurityCadet
    - SeniorOfficer
    - Warden
    - HeadOfSecurity
  item: ClothingEyesGlassesSecurity

- type: loadout
  id: LoadoutSecurityEyesHud
  name: Сек Худ
  description: An alternate job equipment.
  category: Jobs
  cost: 3
  exclusive: true
  jobWhitelist:
    - SecurityOfficer
    - SecurityCadet
    - Warden
    - HeadOfSecurity
  item: ClothingEyesHudSecurity

- type: loadout
  id: LoadoutSecurityShoesBootsCombatFilled
  name: Бойові черевики
  description: An alternate job equipment.
  category: Jobs
  cost: 3
  exclusive: true
  jobWhitelist:
    - SecurityOfficer
    - Warden
    - HeadOfSecurity
  item: ClothingShoesBootsCombatFilled

- type: loadout
  id: LoadoutSecurityShoesJackboots
  name: Чоботи
  description: A really nice, heavy, pair of black boots.
  category: Jobs
  cost: 1
  jobWhitelist:
    - Detective
    - SecurityOfficer
    - SecurityCadet
    - Warden
    - HeadOfSecurity
  item: ClothingShoesBootsJack
