- type: loadout
  id: LoadoutServiceClownUniformJesterAlt
  name: Костюм клоуна
  description: For the fool who knows their place.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Clown
  item: ClothingUniformJumpsuitJesterAlt

- type: loadout
  id: LoadoutServiceClownShoesJester
  name: Черевики клоуна
  description: For the fool who knows their place.
  category: Робота
  cost: 1
  exclusive: true
  jobWhitelist:
    - Clown
  item: ClothingShoesJester

- type: loadout
  id: LoadoutServiceClownHeadJesterHatAlt
  name: Капелюх клоуна
  description: For the fool who knows their place.
  category: Робота
  cost: 1
  exclusive: true
  jobWhitelist:
    - Clown
  item: ClothingHeadHatJesterAlt

- type: loadout
  id: LoadoutServiceBartenderUniformPurple
  name: Фіолетовий комбінезон бармена
  description: An alternate job equipment.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Bartender
  item: ClothingUniformJumpsuitBartenderPurple

- type: loadout
  id: LoadoutServiceBotanistUniformOveralls
  name: Спецодяг
  description: A rugged pair of overalls.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Botanist
  item: ClothingUniformOveralls

- type: loadout
  id: LoadoutServiceLawyerUniformBlueSuit
  name: Синій костюм адвоката
  description: A suit, very legal indeed.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  item: ClothingUniformJumpsuitLawyerBlue

- type: loadout
  id: LoadoutServiceLawyerUniformBlueSkirt
  name: Синя адвокатська спідниця
  description: A skirt, very legal indeed.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  item: ClothingUniformJumpskirtLawyerBlue

- type: loadout
  id: LoadoutServiceLawyerUniformRedSuit
  name: Червоний костюм адвоката
  description: A suit, very legal indeed.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  item: ClothingUniformJumpsuitLawyerRed

- type: loadout
  id: LoadoutServiceLawyerUniformRedSkirt
  name: Червона адвокатська спідниця
  description: A skirt, very legal indeed.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  item: ClothingUniformJumpskirtLawyerRed

- type: loadout
  id: LoadoutServiceLawyerUniformPurpleSuit
  name: Фіолетовий костюм адвоката
  description: A suit, very legal indeed.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  item: ClothingUniformJumpsuitLawyerPurple

- type: loadout
  id: LoadoutServiceLawyerUniformPurpleSkirt
  name: Фіолетова спідниця адвоката
  description: A skirt, very legal indeed.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  item: ClothingUniformJumpskirtLawyerPurple

- type: loadout
  id: LoadoutServiceLawyerUniformGoodSuit
  name: Сірий костюм адвоката
  description: A suit, very legal indeed.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  item: ClothingUniformJumpsuitLawyerGood

- type: loadout
  id: LoadoutServiceLawyerUniformGoodSkirt
  name: Сіра адвокатська спідниця
  description: A skirt, very legal indeed.
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  item: ClothingUniformJumpskirtLawyerGood

- type: loadout
  id: LoadoutServiceReporterUniformJournalist
  name: Журналістський костюм
  description: For the reporter on the case!
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Reporter
  item: ClothingUniformJumpsuitJournalist

- type: loadout
  id: LoadoutServiceReporterUniformDetectivesuit
  name: Крутий костюм
  description: Always reminds you of the one that got away...
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Reporter
  item: ClothingUniformJumpsuitDetective

- type: loadout
  id: LoadoutServiceReporterUniformDetectiveskirt
  name: Крута спідниця
  description: Always reminds you of the one that got away...
  category: Робота
  cost: 2
  exclusive: true
  jobWhitelist:
    - Reporter
  item: ClothingUniformJumpskirtDetective
