- type: entity
  id: DeepFryerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: плата машини для фритюрниці
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: KitchenDeepFryer
      requirements:
        Capacitor: 1
        MatterBin: 1
      materialRequirements:
        Steel: 4
        Glass: 2
        Cable: 4
