- type: entity
  name: ящик для наручників
  parent: BoxCardboard
  id: BoxHandcuff
  description: A box full of handcuffs.
  components:
  - type: StorageFill
    contents:
      - id: Handcuffs
        amount: 6
  - type: Sprite
    layers:
      - state: box_security
      - state: handcuff

- type: entity
  name: коробка світлошумових
  parent: BoxCardboard
  id: BoxFlashbang
  description: 'WARNING: These devices are extremely dangerous and can cause blindness or deafness in repeated use.'
  components:
  - type: StorageFill
    contents:
      - id: GrenadeFlashBang
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: flashbang

- type: entity
  name: коробка секхудів
  parent: BoxCardboard
  id: BoxSechud
  description: A box of security glasses.
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesHudSecurity
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: sechud

- type: entity
  name: коробка зіптаів
  parent: BoxCardboard
  id: BoxZiptie
  description: A box full of zipties.
  components:
  - type: StorageFill
    contents:
      - id: Zipties
        amount: 10
  - type: Sprite
    layers:
      - state: box_security
      - state: ziptie

- type: entity
  name: коробка для криміналістичного паперу
  parent: BoxCardboard
  id: BoxForensicPad
  description: A box of forensic pads.
  components:
  - type: StorageFill
    contents:
      - id: ForensicPad
        amount: 10
  - type: Sprite
    layers:
      - state: box_security
      - state: forensic
